sudo: false

language: python

#addons: &addons
#  apt:
#    packages: timeout

cache:
  apt: true
  ccache: true

## Do not build our sync branch.
#branches:
#  only:
#    - master
#    - Travis*

matrix:
    # Abort all builds on a single failing matrix entry.
    fast_finish: true

    include:
        - python: 2.7
          env: PYTHON=2.7 ROOT=5.34.36
        - python: 3.6
          env: PYTHON=3.6 ROOT=5.34.36
        - python: 2.7
          env: PYTHON=2.7 ROOT=6.12          
        - python: 3.6
          env: PYTHON=3.6 ROOT=6.12
        - language: generic
          os: osx
          osx_image: xcode9.3
          env: PYTHON=2.7 ROOT=5.34.36
        - language: generic
          os: osx
          osx_image: xcode9.3
          env: PYTHON=3.6 ROOT=5.34.36
        - language: generic
          os: osx
          osx_image: xcode9.3
          env: PYTHON=2.7 ROOT=6.12
        - language: generic
          os: osx
          osx_image: xcode9.3
          env: PYTHON=3.6 ROOT=6.12
    allow_failures:
        - os: osx

install:
  # Conda
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then curl --silent http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -o miniconda.sh; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - cd $TRAVIS_BUILD_DIR && pwd && ls -asl && bash ./scripts/build_deps.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - which gcc
  - gcc --version
  - which clang
  - clang --version
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels http://conda.anaconda.org/NLeSC  
  #- conda config --add channels conda-forge
  - conda config --set show_channel_urls yes
  - conda config --show channels 
  - conda create -q -n testenv python=${PYTHON} root=${ROOT} numpy rootpy
  - source activate testenv
  #- conda uninstall -q sqlite libpng libx11 jpeg libtiff
  - conda uninstall --force --yes -q sqlite libpng libx11 jpeg libtiff
  - root -b -q

script:
  - python tests/test_root.py
  - python tests/test_stl.py

on_failure:
  -|
  echo "Showing current directory contents"
  ls -la

#after_success:
#  - python myscript.py some args
