sudo: false

language: python

#addons: &addons
#  apt:
#    packages: timeout

os:
  - linux
  - osx

python:
  - 2.7
  - 3.5
  - 3.6

cache:
  apt: true
  ccache: true

matrix:
    # Abort all builds on a single failing matrix entry.
    fast_finish: true
    include:
        - os: linux
          # dist: trusty
          sudo: false
          env: PYTHON=${TRAVIS_PYTHON_VERSION}
        - os: osx
          osx_image: xcode10
          env: PYTHON=${TRAVIS_PYTHON_VERSION}
    # allow_failures:
    #     - os: osx

install:
  # Conda
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then curl --silent http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -o miniconda.sh; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda install --yes python=${TRAVIS_PYTHON_VERSION}
  - hash -r
  - which python
  - python -V
  - which gcc
  - gcc --version
  - which clang
  - clang --version
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install --yes -q conda-build
  # run build scripts
  - conda config --add channels conda-forge
#  - cd $TRAVIS_BUILD_DIR && conda build ./root5
  - cd $TRAVIS_BUILD_DIR && conda build ./root6
  - cd $TRAVIS_BUILD_DIR && bash ./scripts/build_deps.sh
  # actual package installation
  - conda config --add channels http://conda.anaconda.org/NLeSC  
  #- conda config --add channels conda-forge
  - conda config --set show_channel_urls yes
  - conda config --show channels 
  - conda create -q -n testenv python=${TRAVIS_PYTHON_VERSION} root=${ROOT} numpy rootpy
  - source activate testenv
  - root -b -q

script:
  - python tests/test_root.py
  - python tests/test_stl.py

on_failure:
  -|
  echo "Showing current directory contents"
  ls -la

#after_success:
#  - python myscript.py some args
