package:
  name: h5py
  version: 2.5.0

source:
  fn: h5py-2.5.0.tar.gz                                                  [unix]
  url: https://pypi.python.org/packages/source/h/h5py/h5py-2.4.0.tar.gz  [unix]
  md5: 6e4301b5ad5da0d51b0a1e5ac19e3b74                                  [unix]

build:
    number: 32
    detect_binary_files_with_prefix: True
    string: h5py_25
requirements:
  build:
    -python
    - numpy
    - hdf5         [unix]
    - cython       [unix]
  run:
    - python
    - numpy
    - hdf5         [unix]
    - unittest2    [py26]

about:
  home: http://www.h5py.org/
  license: New BSD (http://opensource.org/licenses/bsd-license.php)
