package:
  name: h5py
  version: 2.5.0

source:
  fn: h5py-2.5.0.tar.gz                                                  [unix]
  url: https://pypi.python.org/packages/source/h/h5py/h5py-2.5.0.tar.gz  [unix]
  md5: 80c9a94ae31f84885cc2ebe1323d6758                                  [unix]

build:
  number: 3
  detect_binary_files_with_prefix: True

requirements:
  build:
    - python
    - numpy
    - hdf5         [unix]
    - cython       [unix]
  run:
    - python
    - numpy
    - hdf5         [unix]
    - unittest2    [py26]

about:
  home: http://www.h5py.org/
  license: New BSD (http://opensource.org/licenses/bsd-license.php)
