package:
  name: cmake
  version: "3.2.3"

source:
  fn: cmake-3.2.3.tar.gz
  url: http://www.cmake.org/files/v3.2/cmake-3.2.3.tar.gz

build:
  number: 1
  detect_binary_files_with_prefix: True

requirements:
  build:
    - system
    - gcc
    - libtool
    - autoconf
    - automake
    - pkg-config
    - python
  run:
    - python

about:
  home: https://github.com/neovim/neovim.git
  summary: Neovim is a project that seeks to aggressively refactor Vim.
