package:
    name: root
    version: 6.14.04

# source:
#     git_url: https://github.com/root-mirror/root
#     git_tag: v6-14-00
#     # patches:

source:
  url: https://root.cern.ch/download/root_v6.14.04.source.tar.gz
#   md5: 58d78513abdcba3f12f0c838d00987bb
#   sha1: 52b4c8edc990a248dbe49b04915bd07a812154cc
  sha256: 463ec20692332a422cfb5f38c78bedab1c40ab4d81be18e99b50cf9f53f596cf

build:
    number: 64
    detect_binary_files_with_prefix: True

requirements:
    build:
        - python
        - numpy==1.15.2
        - cfitsio== 3.430
        - qt==4.8.7

    run:
        - python
        - numpy==1.15.2
        - cfitsio== 3.430
        - qt==4.8.7

#test:

   #files:
   #      - ../tests/test_root.py
   #      - ../tests/test_stl.py

   #commands:
   #      - root -b -q
   #      - which root
   #      - source ${PREFIX}/bin/thisroot.sh
   #      - python test_root.py
   #      - python test_stl.py
         
   #imports:
        #- ROOT
   #requires:
   #      - numpy
   #      - rootpy

about:
    home: http://root.cern.ch/
    license: LGPL v2.1

